services:
  vim:
    build:
      context: .        
      dockerfile: Dockerfile
    volumes:
      - "${HOST_VIM_CONFIG_DIR}/.vimrc:/root/.vimrc"
      - "${HOST_VIM_CONFIG_DIR}/.vim:/root/.vim" 
      - "${HOST_MYAPP_DIR}:/root/workspace"
