x-volumes: &dotfiles_and_app_dir
  - ".bash_history:/root/.bash_history"
  - "${HOST_APP_DIR}:/root/workspace"

x-build-args: &build-args
  args:
    BASE_IMAGE: ${BASE_IMAGE}

x-image-name: &image_name
  name: ${DEV_IMAGE_NAME}

services:
  fancy_bash:
    build:
      context: ..        
      dockerfile: dev-env-setup/Dockerfile
      <<: *build-args
      target: bash
    image: *image_name.name
    environment:
      - HISTCONTROL=ignoredups:ignorespace
      - HISTSIZE=10000
      - HISTFILESIZE=20000
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    command: ["/bin/bash"]
    volumes: *dotfiles_and_app_dir
  
  jupyter:
    build:
      context: ..
      dockerfile: dev-env-setup/Dockerfile
      <<: *build-args
      target: jupyter
    image: *image_name.name
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    volumes: *dotfiles_and_app_dir 

  vim: 
    image: *image_name.name
    build:
      context: ..
      dockerfile: dev-env-setup/Dockerfile
      <<: *build-args
      target: vim_plugins
    working_dir: /root/workspace
    stdin_open: true
    tty: true
    volumes: *dotfiles_and_app_dir