services:
  fancy_bash:
    build:
      context: .        
      dockerfile: Dockerfile
      target: bash
    image: dev-env_bash:latest
    environment:
      - HISTCONTROL=ignoredups:ignorespace
      - HISTSIZE=10000
      - HISTFILESIZE=20000
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    command: ["/bin/bash"]
    volumes: &dotfiles_and_app_dir
    - "${HOST_BASHRC_DIR}/.bashrc:/root/.bashrc"
    - "${HOST_BASHRC_DIR}/starship.toml:/root/.config/starship.toml"
    - ".bash_history:/root/.bash_history"
    - "${HOST_VIM_CONFIG_DIR}/.vimrc:/root/.vimrc"
    - "${HOST_VIM_CONFIG_DIR}/.vim/config:/root/.vim/config"
    - "${HOST_MYAPP_DIR}:/root/workspace"
  
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: jupyter
    image: dev-env_jupyter:latest
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    volumes: *dotfiles_and_app_dir 

  vim:
    image: dev-env_bash:latest
    build:
      context: .        
      dockerfile: Dockerfile
      target: vim
    working_dir: /root/workspace
    stdin_open: true
    tty: true
    volumes: *dotfiles_and_app_dir